### ISSUE TITLE
demo 和实战篇的代码都崩溃

### ISSUE THREAD

**Issue by gzpaiwxc** [koudle/The-Guide-to-the-Flutter#2]
demo 和实战篇的代码有 ListView 的地方(或者是能滑动的widget)往下滑动都会崩溃 , 但是控制台又看不到具体的错误
![1560160595(1)](https://user-images.githubusercontent.com/16586195/59187999-42534c80-8ba9-11e9-939f-0eff0e12131f.jpg)

**Comment by koudle** [comment]
我在我的手机上试了 Huawei Mate 10，没有出现下滑崩溃的问题啊，你能在提供完整的日志吗？

你可以连接 Android Studio 查看日志

**Comment by gzpaiwxc** [comment]
我这个就是 as 上打印出来的日志 , 没有其他有用的信息了 , 不止这个华为 Mate9 Pro , 另一部手机 一加5 也是一样的情况 , 不过 demo 首页的 ListView 滑动到最底部不崩溃 , 但是 ListView 那个章节 ListView.builder 还有 ListView.separated 都是会溃的, dialog 那个章节 showAboutDialog 点击 VIEW LICENSES 往下滑动也是会崩溃 , 还有就是豆瓣的 demo 滑动到最底部也是一样崩溃 , 下面我给出豆瓣 demo 从运行到滑动到最底部崩溃的日志 , 好像有提示数组越界了

**Comment by gzpaiwxc** [comment]
`Running "flutter packages get" in flutter_doubanmovie...            2.5s
Launching lib\main.dart on ONEPLUS A5000 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
I/flutter ( 8044): HotWidgetState initState
I/flutter ( 8044): HotWidgetState build
I/flutter ( 8044): HotWidgetState build
Syncing files to device ONEPLUS A5000...
E/flutter ( 8044): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(40)] java.lang.IndexOutOfBoundsException: Index: 6, Size: 5
E/flutter ( 8044): 	at java.util.ArrayList.get(ArrayList.java:437)
E/flutter ( 8044): 	at io.flutter.view.AccessibilityBridge.updateSemantics(AccessibilityBridge.java:1333)
E/flutter ( 8044): 	at io.flutter.view.AccessibilityBridge$1.updateSemantics(AccessibilityBridge.java:269)
E/flutter ( 8044): 	at io.flutter.embedding.engine.FlutterJNI.updateSemantics(FlutterJNI.java:162)
E/flutter ( 8044): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter ( 8044): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/flutter ( 8044): 	at android.os.Looper.loop(Looper.java:160)
E/flutter ( 8044): 	at android.app.ActivityThread.main(ActivityThread.java:6863)
E/flutter ( 8044): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 8044): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
E/flutter ( 8044): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/flutter ( 8044): 
F/flutter ( 8044): [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(96)] Check failed: CheckException(env). 
F/libc    ( 8044): Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 8044 (ter_doubanmovie), pid 8044 (ter_doubanmovie)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'OnePlus/OnePlus5/OnePlus5:9/PKQ1.180716.001/1905062038:user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 8044, tid: 8044, name: ter_doubanmovie  >>> com.example.flutter_doubanmovie <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(96)] Check failed: CheckException(env). 
'
    x0  0000000000000000  x1  0000000000001f6c  x2  0000000000000006  x3  0000000000000008
    x4  0000000000000000  x5  0000000000000000  x6  0000000000000000  x7  0000000000800000
    x8  0000000000000083  x9  b5ae37e28a1cbfb4  x10 0000000000000000  x11 fffffffc7ffffbdf
    x12 0000000000000001  x13 0000000000000028  x14 ffffffffffffffff  x15 00009ac8d65457bc
    x16 00000073dacd32a8  x17 00000073dabf2954  x18 0000000000000010  x19 0000000000001f6c
    x20 0000000000001f6c  x21 0000007fcc917ed8  x22 00000000ffffffff  x23 000000000000000c
    x24 0000000000000018  x25 00000000ffffffff  x26 000000733abc6a9c  x27 0000000000000018
    x28 0000000000000178  x29 0000007fcc917ec0
    sp  0000007fcc917e80  lr  00000073dabe6084  pc  00000073dabe60ac
backtrace:
    #00 pc 00000000000220ac  /system/lib64/libc.so (abort+116)
    #01 pc 0000000000d34450  /data/app/com.example.flutter_doubanmovie-s-2rN8vTIVvcF1gSZk0Y8Q==/lib/arm64/libflutter.so (offset 0xd20000)
    #02 pc 0000000000d27558  /data/app/com.example.flutter_doubanmovie-s-2rN8vTIVvcF1gSZk0Y8Q==/lib/arm64/libflutter.so (offset 0xd20000)
    #03 pc 0000000000d25f08  /data/app/com.example.flutter_doubanmovie-s-2rN8vTIVvcF1gSZk0Y8Q==/lib/arm64/libflutter.so (offset 0xd20000)
    #04 pc 0000000000d6968c  /data/app/com.example.flutter_doubanmovie-s-2rN8vTIVvcF1gSZk0Y8Q==/lib/arm64/libflutter.so (offset 0xd20000)
    #05 pc 0000000000d35178  /data/app/com.example.flutter_doubanmovie-s-2rN8vTIVvcF1gSZk0Y8Q==/lib/arm64/libflutter.so (offset 0xd20000)
    #06 pc 0000000000d38f4c  /data/app/com.example.flutter_doubanmovie-s-2rN8vTIVvcF1gSZk0Y8Q==/lib/arm64/libflutter.so (offset 0xd20000)
    #07 pc 0000000000014ff8  /system/lib64/libutils.so (android::Looper::pollInner(int)+836)
    #08 pc 0000000000014c18  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+60)
    #09 pc 0000000000127c9c  /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+44)
    #10 pc 00000000003ebfec  /system/framework/arm64/boot-framework.oat (offset 0x3d7000) (android.media.MediaExtractor.seekTo [DEDUPED]+140)
    #11 pc 0000000000002a3c  /dev/ashmem/dalvik-jit-code-cache (deleted) (android.os.MessageQueue.next+204)
    #12 pc 0000000000555788  /system/lib64/libart.so (art_quick_invoke_stub+584)
    #13 pc 00000000000cf6c8  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200)
    #14 pc 000000000027f2b8  /system/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+344)
    #15 pc 00000000002792c0  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+968)
    #16 pc 0000000000524d94  /system/lib64/libart.so (MterpInvokeVirtual+588)
    #17 pc 0000000000547d14  /system/lib64/libart.so (ExecuteMterpImpl+14228)
    #18 pc 0000000000b221be  /system/framework/boot-framework.vdex (android.os.Looper.loop+130)
    #19 pc 0000000000252fc4  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.1133985933+488)
    #20 pc 0000000000258ab8  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
    #21 pc 00000000002792a4  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+940)
    #22 pc 0000000000526298  /system/lib64/libart.so (MterpInvokeStatic+204)
    #23 pc 0000000000547e94  /system/lib64/libart.so (ExecuteMterpImpl+14612)
    #24 pc 000000000039ffa2  /system/framework/boot-framework.vdex (android.app.ActivityThread.main+214)
    #25 pc 0000000000252fc4  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.1133985933+488)
    #26 pc 0000000000515628  /system/lib64/libart.so (artQuickToInterpreterBridge+1020)
    #27 pc 000000000055e8fc  /system/lib64/libart.so (art_quick_to_interpreter_bridge+92)
    #28 pc 0000000000555a4c  /system/lib64/libart.so (art_quick_invoke_static_stub+604)
    #29 pc 00000000000cf6e8  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+232)
    #30 pc 000000000045cd00  /system/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104)
    #31 pc 000000000045e754  /system/lib64/libart.so (art::InvokeMethod(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned long)+1440)
    #32 pc 00000000003ee5b0  /system/lib64/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*)+52)
    #33 pc 000000000011f6d4  /system/framework/arm64/boot-core-oj.oat (offset 0x115000) (java.lang.Class.getDeclaredMethodInternal [DEDUPED]+180)
    #34 pc 0000000000555788  /system/lib64/libart.so (art_quick_invoke_stub+584)
    #35 pc 00000000000cf6c8  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200)
    #36 pc 000000000027f2b8  /system/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+344)
    #37 pc 00000000002792c0  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+968)
    #38 pc 0000000000524d94  /system/lib64/libart.so (MterpInvokeVirtual+588)
    #39 pc 0000000000547d14  /system/lib64/libart.so (ExecuteMterpImpl+14228)
    #40 pc 0000000000c475c6  /system/framework/boot-framework.vdex (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+22)
    #41 pc 0000000000252fc4  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.1133985933+488)
    #42 pc 0000000000515628  /system/lib64/libart.so (artQuickToInterpreterBridge+1020)
    #43 pc 000000000055e8fc  /system/lib64/libart.so (art_quick_to_interpreter_bridge+92)
    #44 pc 0000000000c0b450  /system/framework/arm64/boot-framework.oat (offset 0x3d7000) (com.android.internal.os.ZygoteInit.main+3088)
    #45 pc 0000000000555a4c  /system/lib64/libart.so (art_quick_invoke_static_stub+604)
    #46 pc 00000000000cf6e8  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+232)
    #47 pc 000000000045cd00  /system/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104)
    #48 pc 000000000045c960  /system/lib64/libart.so (art::InvokeWithVarArgs(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+424)
    #49 pc 0000000000361b64  /system/lib64/libart.so (art::JNI::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+652)
    #50 pc 00000000000b28cc  /system/lib64/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+116)
    #51 pc 00000000000b53b4  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+948)
    #52 pc 000000000000251c  /system/bin/app_process64 (main+2000)
    #53 pc 00000000000c8418  /system/lib64/libc.so (__libc_init+88)
Lost connection to device.
`

**Comment by koudle** [comment]
可以看这个 https://github.com/flutter/flutter/issues/32047
是 Flutter 的bug，你可以更新到最新版，你的 Flutter 版本是 v1.5.4-hotfix.2 吗？还是用的其他的？

**Comment by koudle** [comment]
建议 Flutter 的版本使用 v1.5.4-hotfix.2  的，不是的话就更新到最新版本

**Comment by gzpaiwxc** [comment]
我的 flutter 版本就是 1.5.4-hotfix.2 的呀 
![1560311418(1)](https://user-images.githubusercontent.com/16586195/59325257-eb6a8600-8d14-11e9-95c8-69f4d1a17db5.jpg)

**Comment by buildsoftwareb** [comment]
嘎嘎嘎
## 
# 
### ****__` `
